#!/bin/bash
#
#Aastaaegade ülesanne
#
read -p "Sisesta palun kuu: " kuu
if test $kuu -ge 1 -a $kuu -lt 2
then
      echo "on talv"
elif test $kuu -ge 3 -a $kuu -lt 5
then
      echo "on kevad"
elif test $kuu -ge 6 -a $kuu -lt 8
then
      echo "on suvi"
elif test $kuu -ge 9 -a $kuu -lt 11
then
      echo "on sügis"
elif test $kuu -ge 12
then
     echo "on talv"
fi
#skripti lõpp
